from __future__ import annotations

import base64
import os

import pytest
from cryptography.exceptions import InvalidTag

from pigeonhole_worker.crypto import decrypt_token, encrypt_token, key_from_env

KEY = bytes([7]) * 32

# Generated by web/lib/crypto (Node.js) with the same fixed key/iv. Guarantees
# the worker can decrypt what the web app encrypts.
TS_VECTOR_PACKED = base64.b64decode(
    "AwMDAwMDAwMDAwMDfLclzdR1E5WoAIrYQzuER0aMzHApBTIjFCc2PYwy0niCV4WBmWUL/po="
)
TS_VECTOR_PLAINTEXT = "cross-language-token-🎵"


def test_round_trip() -> None:
    packed = encrypt_token("BQD-secret-token", KEY)
    assert decrypt_token(packed, KEY) == "BQD-secret-token"


def test_decrypts_typescript_ciphertext() -> None:
    assert decrypt_token(TS_VECTOR_PACKED, KEY) == TS_VECTOR_PLAINTEXT


def test_random_iv_gives_distinct_ciphertexts() -> None:
    assert encrypt_token("same", KEY) != encrypt_token("same", KEY)


def test_rejects_tampered_payload() -> None:
    packed = bytearray(encrypt_token("secret", KEY))
    packed[-1] ^= 0xFF
    with pytest.raises(InvalidTag):
        decrypt_token(bytes(packed), KEY)


def test_rejects_wrong_key() -> None:
    packed = encrypt_token("secret", KEY)
    with pytest.raises(InvalidTag):
        decrypt_token(packed, os.urandom(32))


def test_rejects_short_payload() -> None:
    with pytest.raises(ValueError, match="too short"):
        decrypt_token(b"tiny", KEY)


def test_key_from_env_validates(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("TOKEN_ENCRYPTION_KEY", raising=False)
    with pytest.raises(RuntimeError, match="not set"):
        key_from_env()
    monkeypatch.setenv("TOKEN_ENCRYPTION_KEY", base64.b64encode(b"short").decode())
    with pytest.raises(RuntimeError, match="32 bytes"):
        key_from_env()
    monkeypatch.setenv("TOKEN_ENCRYPTION_KEY", base64.b64encode(KEY).decode())
    assert key_from_env() == KEY
